//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingWebApi.Infrastructure.SqlScripts.ApartamentSql {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApartmentSqlResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApartmentSqlResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BookingWebApi.Infrastructure.SqlScripts.ApartamentSql.ApartmentSqlResources", typeof(ApartmentSqlResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///    PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY &quot;Area&quot;) AS &quot;FirstQuartile&quot;,
        ///    PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY &quot;Area&quot;) AS &quot;Median&quot;,
        ///    PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY &quot;Area&quot;) AS &quot;ThirdQuartile&quot;
        ///FROM &quot;Apartaments&quot;;.
        /// </summary>
        internal static string AreaQuantiles {
            get {
                return ResourceManager.GetString("AreaQuantiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT &quot;Bedrooms&quot;, AVG(&quot;Area&quot;) AS &quot;AverageArea&quot;
        ///FROM &quot;Apartaments&quot;
        ///GROUP BY &quot;Bedrooms&quot;.
        /// </summary>
        internal static string AverageAreaByBedrooms {
            get {
                return ResourceManager.GetString("AverageAreaByBedrooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT &quot;HostId&quot;, COUNT(*) AS &quot;ApartamentCount&quot;,
        ///AVG(&quot;Area&quot;) AS &quot;AverageArea&quot;
        ///FROM &quot;Apartaments&quot;
        ///GROUP BY &quot;HostId&quot;
        ///HAVING AVG(&quot;Area&quot;) &gt; 50;.
        /// </summary>
        internal static string HostsWithLargeAverageApartments {
            get {
                return ResourceManager.GetString("HostsWithLargeAverageApartments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT PERCENTILE_CONT(0.5) 
        ///WITHIN GROUP (ORDER BY &quot;Area&quot;) AS MediaArea
        ///FROM &quot;Apartaments&quot;;.
        /// </summary>
        internal static string MedianArea {
            get {
                return ResourceManager.GetString("MedianArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT &quot;SourceCompanyId&quot;,
        ///SUM(&quot;Area&quot;) AS &quot;TotalArea&quot;,
        ///COUNT(*) AS &quot;ApartamentCount&quot;
        ///FROM &quot;Apartaments&quot;
        ///GROUP BY &quot;SourceCompanyId&quot;.
        /// </summary>
        internal static string TotalAreaAndCountBySourceCompany {
            get {
                return ResourceManager.GetString("TotalAreaAndCountBySourceCompany", resourceCulture);
            }
        }
    }
}
