name: CI/CD Pipeline for AWS Elastic Beanstalk

on:
  push:
    branches:
      - main
       - feature/ci-cd
  pull_request:

jobs:
  deploy-to-aws:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0

      - name: Restore dependencies
        run: dotnet restore BookingProject/BookingWebAPI/BookingWebAPI.sln

      - name: Build project
        run: dotnet build BookingProject/BookingWebAPI/BookingWebAPI.sln --configuration Release --no-restore

      - name: Publish application
        run: dotnet publish BookingProject/BookingWebAPI/BookingWebAPI.sln --configuration Release --output ./publish

      - name: Compress published application
        run: zip -r BookingWebAPI.zip ./publish

      - name: Upload to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp BookingWebAPI.zip s3://elasticbeanstalk-us-east-2-127214158843/booking-webapi/BookingWebAPI_${{ github.run_id }}.zip

      - name: Verify S3 Upload
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 ls s3://elasticbeanstalk-us-east-2-127214158843/booking-webapi/BookingWebAPI_${{ github.run_id }}.zip || exit 1

      - name: Create new Elastic Beanstalk application version
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name bookingwebapi \
            --version-label ${{ github.run_id }} \
            --source-bundle S3Bucket=elasticbeanstalk-us-east-2-127214158843,S3Key=booking-webapi/BookingWebAPI_${{ github.run_id }}.zip

      - name: Update Elastic Beanstalk environment
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws elasticbeanstalk update-environment \
            --environment-name Development \
            --version-label ${{ github.run_id }}

      - name: Confirm deployment status
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws elasticbeanstalk describe-environments --application-name bookingwebapi
