name: CI/CD Pipeline for AWS Elastic Beanstalk

on:
  push:
    branches:
      - main
      - feature/ci-cd
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0

      - name: Restore dependencies
        run: dotnet restore BookingProject/BookingWebAPI/BookingWebAPI.sln

      - name: Build project
        run: dotnet build BookingProject/BookingWebAPI/BookingWebAPI.sln --no-restore --configuration Release

      - name: Publish project to ZIP
        run: |
          dotnet publish BookingProject/BookingWebAPI/BookingWebAPI.sln \
            --configuration Release \
            --output ./publish
          cd publish
          zip -r ../BookingWebAPI.zip .
          cd ..

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Upload ZIP to S3
        run: |
          aws s3 cp BookingWebAPI.zip s3://elasticbeanstalk-us-east-2-127214158843/booking-webapi/BookingWebAPI_${{ github.run_id }}.zip

      - name: Deploy to Elastic Beanstalk
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name BookingWebAPI \
            --version-label ${GITHUB_RUN_ID} \
            --source-bundle S3Bucket="elasticbeanstalk-us-east-2-127214158843",S3Key="booking-webapi/BookingWebAPI_${{ github.run_id }}.zip"
          aws elasticbeanstalk update-environment \
            --environment-name Development \
            --version-label ${GITHUB_RUN_ID}
